version: '3'
services:
  calc-server-mysql:
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=calcserver
      - MYSQL_PASSWORD=calcserver
      - MYSQL_DATABASE=calculationserver
    ports:
      - 3306:3306